name: RunTime APK Builder
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Updated from v3 to v4
      - uses: actions/checkout@v4 
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Make gradlew executable
        # This fixes the "No such file or directory" error from the image
        run: chmod +x ./gradlew
        
      - name: Build
        run: ./gradlew assembleDebug
        
      # Updated from v3 to v4
      - name: Archive
        uses: actions/upload-artifact@v4 
        with:
          name: RunTime-2026-APK
          path: app/build/outputs/apk/debug/app-debug.apk
